# Nome da aplicação
spring.application.name=meu-projeto-api

# Configurações do Banco de Dados H2 (Em memória)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Permite que as tabelas sejam criadas automaticamente com base nas suas Entities
spring.jpa.hibernate.ddl-auto=update

# Ativa o console do H2 para você ver o banco no navegador se quiser
spring.h2.console.enabled=true

# Mostra o SQL que o Hibernate está gerando no console (ajuda muito a aprender!)
spring.jpa.show-sql=true